In [1]:
from __future__ import division, print_function
# отключим всякие предупреждения Anaconda
import warnings
warnings.filterwarnings('ignore')
import os
import pickle
import numpy as np
import itertools
import pandas as pd
from collections import Counter
from scipy.sparse import csr_matrix
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, GridSearchCV
import xgboost as xgb

In [2]:
# Поменяйте на свой путь к данным
# PATH_TO_DATA = '/tmp/working/machinleaning/ml/6/ident/kaggle_data/'
PATH_TO_DATA = '/tmp/working/machinleaning/ml/6/ident/kaggle_data/'
KAGGLE_DATA = 'kaggle_data/'

In [12]:
with open(os.path.join(PATH_TO_DATA, 
                       'X_sparse_30users.pkl'), 'rb') as X30_pkl:
    X_train_sparse = pickle.load(X30_pkl)
with open(os.path.join(PATH_TO_DATA, 
                       'y_30users.pkl'), 'rb') as y30_pkl:
    y = pickle.load(y30_pkl)

In [3]:
# with open(os.path.join(PATH_TO_DATA, 'X_train_sparse.pkl'), 'rb') as X_train_sparse_pkl:
#     X_train_sparse = pickle.load(X_train_sparse_pkl)
# with open(os.path.join(PATH_TO_DATA, 'X_test_sparse.pkl'), 'rb') as X_test_sparse_pkl:
#     X_test_sparse = pickle.load(X_test_sparse_pkl)
# with open(os.path.join(PATH_TO_DATA, 'train_target.pkl'), 'rb') as train_target_pkl:
#     y = pickle.load(train_target_pkl)

In [13]:
X_train, X_valid, y_train, y_valid = train_test_split(X_train_sparse, y, 
                                                      test_size=0.3, 
                                                     random_state=17, stratify=y)

In [14]:
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=17)

In [11]:
xgb_scoring

[array([ 0.06860615,  0.06633682,  0.06781296]),
 array([ 0.13221171,  0.13349435,  0.13270923])]

In [28]:
%%time
estimator = xgb.XGBClassifier(learning_rate=0.1, max_depth=6,\
                                  n_jobs=3, n_estimators=20, min_child_weight=3)
score = cross_val_score(estimator, X_train, y_train, verbose=3,
                                         scoring = 'accuracy', cv = skf)    

[CV]  ................................................................
[CV] ....................... , score=0.4651955507714388, total=  10.6s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   10.7s remaining:    0.0s


[CV] ....................... , score=0.4653918664152976, total=   9.3s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:   20.0s remaining:    0.0s


[CV] ....................... , score=0.4564240790655885, total=   9.6s
CPU times: user 1min 14s, sys: 1.62 s, total: 1min 16s
Wall time: 29.6 s


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:   29.6s finished


In [29]:
score

array([ 0.46519555,  0.46539187,  0.45642408])

In [93]:
sgd_svm = SGDClassifier(loss='log',penalty='elasticnet',verbose=0,alpha=0.0001,random_state=7,n_jobs=-1)

In [94]:
score = cross_val_score(sgd_svm, X_train, y_train, verbose=3,
                                         scoring = 'accuracy', cv = skf)    

[CV]  ................................................................
[CV] ....................... , score=0.5749910297811267, total=   1.1s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    1.1s remaining:    0.0s


[CV] ....................... , score=0.5631564772421223, total=   1.1s
[CV]  ................................................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    2.2s remaining:    0.0s


[CV] ........................ , score=0.578796046720575, total=   1.0s


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    3.2s finished


In [95]:
score

array([ 0.57499103,  0.56315648,  0.57879605])

In [98]:
sgd_svm.fit(X_train,y_train)

SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='log', max_iter=None, n_iter=None,
       n_jobs=-1, penalty='elasticnet', power_t=0.5, random_state=7,
       shuffle=True, tol=None, verbose=0, warm_start=False)

In [99]:
sgd_svm.score(X_valid,y_valid)

0.587906716938975